meta:
  output_dir: "/home/melandur/Downloads"
  input_file: "/home/melandur/Data/Myocarditis/Final_Regional_Database_reduced.xlsx"
  name: "phenomapping" # experiment name (i.e. file name in which to store merged data)
  target_label: ["a", "b", "c", "d"] # which column to use as label for exploration, feature reduction and analysis
  seed: [1, 2, 3] # random seed
  logging_level: "DEBUG" # TRACE, DEBUG, INFO, WARNING, ERROR, CRITICAL

impute:
  active: True # whether to impute missing values
  method: ["mean"] # "mean" # method to use for imputation, can be 'mean', 'median', 'most_frequent', 'constant'
  constant: 0 # constant to use for imputation if method is 'constant'

data_split:
  active: True # whether to split data into training and testing sets
  test_size: 0.2 # fraction of data to use for testing

exploration:
  active: True # whether to perform exploratory analysis
  variance_thresh: 0.9 # remove binary features with same value in more than variance_thresh subjects
  corr_method: "pearson" # correlation method
  corr_thresh: 0.6 # threshold above which correlated features are removed
  corr_drop_features: True # whether to drop highly correlated features
  scoring:
    {
      "classification": "average_precision",
      "regression": "neg_mean_absolute_error",
    }
  class_weight: "balanced"
  auto_norm_method:
    binary: "z_score_norm"
    continuous: "min_max_norm"
    object: "z_score_norm"
    datatime: "z_score_norm"


  jobs: [
      # ['variance_threshold', 'z_score_norm', 'correlation', 'fr_all', 'pca', 'tsne', 'umap'],
      # ['variance_threshold', 'z_score_norm', 'fr_all', 'pca', 'tsne', 'umap'],
      ["variance_threshold", "z_score_norm", "fr_forest"],
    ]

verification:
  active: True # whether to perform verification analysis
  explore_frac: 0 # fraction of data to use for exploration, the rest is used for verification (set to 0 to use all training data for exploration and verification)
  oversample: False # whether to oversample minority class to balance training set
  models:
    {
      "logistic_regression": True,
      "forest": False,
      "extreme_forest": False,
    }
  param_grids:
    {
      "logistic_regression":
        {
          "penalty": ["l1", "l2"],
          "C": [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000],
          "solver": ["saga"], # supports both l1 and l2 penalties
        },
      "forest":
        {
          "bootstrap": [True, False],
          "max_depth": [10, 50, 100, null],
          "max_features": ["sqrt", "log2", null],
          "n_estimators": [100, 500, 1000],
        },
    }
