raw_dir: '/home/sebalzer/Documents/Mike_init/tests/test/0_raw'
out_dir: '/home/sebalzer/Documents/Mike_init/tests/test/'
mdata_src: '/home/sebalzer/Documents/Mike_init/Final_Regional_Database_reduced.xlsx'  # metadata source directory