raw_dir: '/home/sebalzer/Documents/Mike_init/ATTRAS/'
out_dir: '/home/sebalzer/Documents/Mike_init/ATTRAS/'
mdata_src: '/home/sebalzer/Documents/Mike_init/Final_Regional_Database_reduced.xlsx'  # metadata source directory