# raw_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests/train/0_raw'
# out_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests/train'
# raw_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests_small/train/0_raw'
# out_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests_small/train'
raw_dir: '/home/sebalzer/Documents/Mike_init/tests/train/0_raw'
out_dir: '/home/sebalzer/Documents/Mike_init/tests/train/'
mdata_src: '/home/sebalzer/Documents/Mike_init/Final_Regional_Database_reduced.xlsx'  # metadata source directory
# raw_dir: '/home/sebalzer/Documents/Excel_mergen/Strain'
# out_dir: '/home/sebalzer/Documents/Excel_mergen/'