# raw_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests/train/0_raw'
# out_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests/train'
# raw_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests_small/train/0_raw'
# out_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests_small/train'
raw_dir: '/home/melandur/Data/Myocarditis/new/0_raw'
out_dir: '/home/melandur/Data/Myocarditis/new'
# raw_dir: '/home/sebalzer/Documents/Mike_init/tests_small/train/0_raw'
# out_dir: '/home/sebalzer/Documents/Mike_init/tests_small/train/'
# raw_dir: '/home/sebalzer/Documents/Excel_mergen/Strain'
# out_dir: '/home/sebalzer/Documents/Excel_mergen/'